### ISSUE TITLE
Current release 0.5.0 is not building

### ISSUE THREAD

**Issue by marcusficner** [DoccZz/docc2html#18]
Hi!

The dependency to DocCArchive in Package.swift

```
.package(url  : "https://github.com/DoccZz/DocCArchive.git",
             from : "0.3.2"),
```

contains a `.link` case in https://github.com/DoccZz/DocCArchive/blob/develop/Sources/DocCArchive/Schema_0_1/References/Reference.swift#L24

which is only considered in the latest commit https://github.com/DoccZz/docc2html/commit/5588eb6377339e8a982a74d5dfb34f2ed315f5a0 here.

Please release a new version. Thank you!

**Comment by helje5** [comment]
And 0.5.2 is out. Thanks!
