### ISSUE TITLE
Combining Doccarchives

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [DoccZz/docc2html#8]
We've got multiple modules that all really should reference each other. Any chance this could be adapted to combine multiple doccarchives?

**Comment by helje5** [comment]
docc2html already accepts multiple archives and outputs them all into the same target folder (not really tested though, but should work). It doesn't generate a combined index.html or sth though, you'd have to provide that.

But you probably want cross references between the archives, which I don't think is (easily) possible. I think you'd have to create a single umbrella docc archive in Xcode for that, but no idea.
